class_name TankUI
extends CanvasLayer
## Tank controls: population readout, sound, pause, the tank switcher, and the picker.
##
## The picker is built from the tank's own species and decor lists rather than authored,
## so a new .tres dropped into `available_species` appears here with no further work.
## It is a scrolling strip of art tiles: the roster is eight entries and growing, and a
## row of text buttons stopped fitting a phone's width at six.
##
## Nothing here draws its own colours. Every surface comes from the theme generated by
## tools/generate_theme.gd, which is the one place to change how the app looks.
##
## Anything that covers the tank and does NOT want taps must be MOUSE_FILTER_IGNORE. A
## Control defaults to STOP, and a full-rect container left at the default silently
## swallows every tap meant for the tank — fish simply stop spawning and nothing reports
## an error. The few controls that block deliberately (the dock, the switcher, the
## population chip) are in the `ui_blocker` group, and test/smoke_test.gd holds the line
## that nothing else does.

## Sizes here are in viewport UNITS, and a unit is about 0.56 of a point on a phone —
## see UNITS_PER_POINT in tools/generate_theme.gd, which is where the conversion and the
## reason for it live. The point value is given after each one.

## Fallback padding where a platform reports no safe area (desktop, and the editor).
const BASE_MARGIN: int = 18   # 10pt

## Ceiling on one safe-area inset, as a fraction of that screen dimension.
##
## An iPhone 15 Pro's notch and home indicator are 141px on a 2556px screen — 5.5%
## each — so 12% is generous for anything a phone actually reports, and rejects a
## platform that means something else by "safe area".
const MAX_INSET_FRACTION: float = 0.12

## Width a picker tile's artwork is capped to. Below about 18pt the smaller fish are a
## smudge, and the tall narrow ones — kelp — are a line.
const TILE_ART: int = 58      # 32pt
## How much of the card the tank list may take before it starts scrolling inside it.
const LIST_MAX_HEIGHT: float = 560.0   # 311pt

## A floor, not a width: the tiles size to their names, so "Anemonefish" gets the room
## it needs and "Kelp" does not reserve it.
const TILE_WIDTH: int = 101   # 56pt

const ICON_SOUND_ON: Texture2D = preload("res://assets/textures/ui/sound_on.png")
const ICON_SOUND_OFF: Texture2D = preload("res://assets/textures/ui/sound_off.png")
const ICON_TANKS: Texture2D = preload("res://assets/textures/ui/tanks.png")
const ICON_PAUSE: Texture2D = preload("res://assets/textures/ui/pause.png")
const ICON_PLAY: Texture2D = preload("res://assets/textures/ui/play.png")
const ICON_CLOSE: Texture2D = preload("res://assets/textures/ui/close.png")
const ICON_FEED: Texture2D = preload("res://assets/textures/ui/feed.png")
const ICON_FISH: Texture2D = preload("res://assets/textures/ui/fish.png")
const ICON_UNDO: Texture2D = preload("res://assets/textures/ui/undo.png")
const ICON_TECH: Texture2D = preload("res://assets/textures/ui/tech.png")
const ICON_REMOVE: Texture2D = preload("res://assets/textures/ui/remove.png")
## The strike has no glyph of its own yet; the anemone stands in, tinted by the theme
## like every other tile. Drawing one belongs with the rest of tools/art/draw_ui_icons.py.
const ICON_COLONY: Texture2D = preload("res://assets/textures/anemone.png")
## What a reef looks like once a bleach has been through it.
const BLEACHED: Color = Color(0.92, 0.94, 0.9)
## Seconds an event line stays up before it fades.
const FEED_HOLD: float = 4.5
## Below this share a faction is left off the standings, so a seedling does not push a
## real contender onto a second line.
const MIN_STANDING: float = 0.005

@export var aquarium_path: NodePath = ^"../Aquarium"

var _aquarium: Aquarium
var _group := ButtonGroup.new()

@onready var safe: MarginContainer = $Root/Safe
@onready var population_label: Label = %Population
@onready var fish_icon: TextureRect = %FishIcon
@onready var undo_button: Button = %Undo
@onready var sound_button: Button = %Sound
@onready var tanks_button: Button = %Tanks
@onready var pause_button: Button = %Pause
@onready var dock_safe: MarginContainer = %DockSafe
@onready var hint: Label = %Hint
@onready var picker: HBoxContainer = %Picker
@onready var standings: HFlowContainer = %Standings
@onready var top_bar: HBoxContainer = $Root/Safe/Stack/TopBar

var _feed: Label
var _feed_tween: Tween
var _tech_sheet: Control
var _tech_list: VBoxContainer
@onready var sheet: Control = $Root/Sheet
@onready var sheet_safe: MarginContainer = %SheetSafe
@onready var tank_list: VBoxContainer = %TankList
@onready var list_scroll: ScrollContainer = %ListScroll
@onready var close_button: Button = %Close
@onready var new_tank_button: Button = %NewTank

func _ready() -> void:
	_aquarium = get_node_or_null(aquarium_path) as Aquarium
	if _aquarium == null:
		push_error("UI could not find an Aquarium at %s" % aquarium_path)
		return

	fish_icon.texture = ICON_FISH
	tanks_button.icon = ICON_TANKS
	close_button.icon = ICON_CLOSE
	undo_button.icon = ICON_UNDO
	undo_button.tooltip_text = "Undo"

	pause_button.pressed.connect(_aquarium.toggle_paused)
	undo_button.pressed.connect(_undo)
	_aquarium.undo_changed.connect(_on_undo_changed)
	_on_undo_changed(_aquarium.can_undo())
	tanks_button.pressed.connect(_toggle_sheet)
	close_button.pressed.connect(_toggle_sheet)
	new_tank_button.pressed.connect(_create)
	sound_button.pressed.connect(_toggle_sound)
	_refresh_sound_button()
	_on_paused_changed(_aquarium.is_paused())
	_aquarium.paused_changed.connect(_on_paused_changed)
	_aquarium.population_changed.connect(_on_population_changed)
	_aquarium.species_selected.connect(_on_species_selected)
	_aquarium.territory_changed.connect(_on_territory_changed)
	_aquarium.faction_evolved.connect(_on_faction_evolved)
	_aquarium.faction_descended.connect(_on_faction_descended)
	_aquarium.faction_ascended.connect(_on_faction_ascended)
	_aquarium.faction_extinct.connect(_on_faction_extinct)
	_build_feed()
	_build_tech_sheet()
	# Drawn once now from whatever the map already holds. The Aquarium restores its save
	# in its own _ready, which runs before this one, so the territory_changed those
	# restored colonies emitted has already gone past. Without this a reopened tank shows
	# no standings until the next territory pass — and none at all while it is paused,
	# because a paused tank does not run one.
	_on_territory_changed(_aquarium.colonies().size())

	_build_picker()
	_on_population_changed(_aquarium.population())

	get_viewport().size_changed.connect(_apply_safe_area)
	_apply_safe_area()

## Undoing a removal puts a fish back, so the picker's hint can go stale with it — the
## hint is read from the tank rather than remembered, so refreshing it is enough.
func _undo() -> void:
	_aquarium.undo()
	_refresh_hint()

func _on_undo_changed(available: bool) -> void:
	undo_button.disabled = not available

func _toggle_sound() -> void:
	var main := get_parent()
	main.set_muted(not main.is_muted())
	_refresh_sound_button()

func _refresh_sound_button() -> void:
	var muted: bool = get_parent().is_muted()
	sound_button.icon = ICON_SOUND_OFF if muted else ICON_SOUND_ON
	sound_button.tooltip_text = "Sound off" if muted else "Sound on"

func _toggle_sheet() -> void:
	sheet.visible = not sheet.visible
	if sheet.visible:
		_build_tank_list()

## One row per saved tank, plus the button to make a new one.
##
## Rebuilt on open rather than kept in sync: the list is short, opening it is rare, and
## a rebuild cannot drift from what is actually on disk.
func _build_tank_list() -> void:
	for child in tank_list.get_children():
		child.queue_free()

	var active := TankStore.active_slot()
	var only_tank := TankStore.slots().size() <= 1
	# One group over the rows, so the tank you are in stays lit and cannot be un-lit by
	# tapping it. Disabling that row instead drew it grey, which reads as "this tank is
	# broken" rather than "this is the one you are looking at".
	var rows := ButtonGroup.new()
	rows.allow_unpress = false
	for slot: Variant in TankStore.slots():
		var id: String = str(slot.get("id", ""))
		var name: String = str(slot.get("name", id))

		# Two lines, not three columns. The name is whatever the player typed, and on a
		# phone a name, a count and two buttons on one line left the name about 150pt
		# wide: "My Aquarium" came back as "My Aquari" with the fish count gone. Giving
		# the name the card's full width and dropping the actions beneath it costs one
		# row of height and stops the card from depending on how anyone names a tank.
		var row := PanelContainer.new()
		row.theme_type_variation = &"Row"
		var lines := VBoxContainer.new()
		lines.mouse_filter = Control.MOUSE_FILTER_IGNORE
		lines.add_theme_constant_override("separation", 11)
		row.add_child(lines)

		var open := Button.new()
		open.text = "%s  ·  %d fish" % [name, _fish_in(id)]
		open.focus_mode = Control.FOCUS_NONE
		open.alignment = HORIZONTAL_ALIGNMENT_LEFT
		open.theme_type_variation = &"RowButton"
		# A guard, not the layout: the name has the whole row now, and this only bites
		# on a name far longer than the card.
		open.clip_text = true
		open.toggle_mode = true
		open.button_group = rows
		open.button_pressed = id == active
		open.pressed.connect(_switch_to.bind(id))
		lines.add_child(open)

		var actions := HBoxContainer.new()
		actions.mouse_filter = Control.MOUSE_FILTER_IGNORE
		actions.alignment = BoxContainer.ALIGNMENT_END
		actions.add_theme_constant_override("separation", 14)
		lines.add_child(actions)

		var rename := Button.new()
		rename.text = "Rename"
		rename.theme_type_variation = &"SmallButton"
		rename.focus_mode = Control.FOCUS_NONE
		rename.pressed.connect(_begin_rename.bind(id))
		actions.add_child(rename)

		var remove := Button.new()
		remove.text = "Delete"
		remove.theme_type_variation = &"DangerButton"
		remove.focus_mode = Control.FOCUS_NONE
		# Never offer to delete the only tank: it would leave the app with nowhere to
		# save and the next launch would silently make a fresh one.
		remove.disabled = only_tank
		remove.pressed.connect(_confirm_delete.bind(id, name))
		actions.add_child(remove)

		tank_list.add_child(row)

	new_tank_button.disabled = TankStore.slots().size() >= TankStore.MAX_SLOTS
	# The list is as tall as it needs to be, up to a cap. Twelve slots at full height
	# would be a card taller than the phone; a fixed height would be four empty rows
	# under the single tank almost everyone has.
	list_scroll.custom_minimum_size.y = minf(
		tank_list.get_combined_minimum_size().y, LIST_MAX_HEIGHT)

func _fish_in(slot_id: String) -> int:
	# The tank on screen has not necessarily autosaved since its last birth, so its own
	# count is the live one and the file's is stale. A tank made a second ago read
	# "0 fish" with fifty of them swimming behind the card.
	if slot_id == TankStore.active_slot():
		return _aquarium.population()
	return TankStore.read(slot_id).get("fish", []).size()

## Saving the current tank before leaving it is the whole contract of switching.
func _switch_to(slot_id: String) -> void:
	# Tapping the row you are already in is a no-op, not a reload: the rows are a
	# radio group now rather than one disabled button, so the tap reaches here.
	if slot_id == TankStore.active_slot():
		return
	_aquarium.save()
	TankStore.set_active(slot_id)
	_reload()

func _create() -> void:
	_aquarium.save()
	var id := TankStore.create_slot(_next_tank_name())
	if id == "":
		return
	_reload()

## The first "Aquarium N" no tank is already using.
##
## Numbering by the slot count repeats a name as soon as one is deleted: two tanks both
## called "Aquarium 2" is a switcher that cannot tell you which is which.
func _next_tank_name() -> String:
	var taken: Dictionary = {}
	for slot: Variant in TankStore.slots():
		taken[str(slot.get("name", ""))] = true
	var index := TankStore.slots().size() + 1
	while taken.has("Aquarium %d" % index):
		index += 1
	return "Aquarium %d" % index

## Deleting a tank destroys years of a player's fish in one tap, so it asks first.
func _confirm_delete(slot_id: String, name: String) -> void:
	var dialog := ConfirmationDialog.new()
	dialog.title = "Delete aquarium"
	dialog.dialog_text = "Delete \"%s\" and every fish in it?\n\nThis cannot be undone." % name
	dialog.ok_button_text = "Delete"
	dialog.confirmed.connect(_delete.bind(slot_id))
	dialog.visibility_changed.connect(func() -> void:
		if not dialog.visible:
			dialog.queue_free())
	add_child(dialog)
	dialog.popup_centered()

func _begin_rename(slot_id: String) -> void:
	var current := slot_id
	for slot: Variant in TankStore.slots():
		if slot.get("id", "") == slot_id:
			current = str(slot.get("name", slot_id))

	var dialog := AcceptDialog.new()
	dialog.title = "Rename aquarium"
	var field := LineEdit.new()
	field.text = current
	field.custom_minimum_size = Vector2(260, 0)
	field.select_all()
	dialog.add_child(field)
	dialog.ok_button_text = "Rename"
	dialog.confirmed.connect(func() -> void:
		var name := field.text.strip_edges()
		if name != "":
			TankStore.rename_slot(slot_id, name)
			_build_tank_list())
	dialog.visibility_changed.connect(func() -> void:
		if not dialog.visible:
			dialog.queue_free())
	add_child(dialog)
	dialog.popup_centered()
	field.grab_focus()

func _delete(slot_id: String) -> void:
	var was_active := slot_id == TankStore.active_slot()
	TankStore.delete_slot(slot_id)
	if was_active:
		_reload()
	else:
		_build_tank_list()

## Reloading the scene is how a tank is swapped: the Aquarium builds itself from the
## active slot in _ready, so there is no second code path for "load a different tank"
## that could drift from the one used at launch.
func _reload() -> void:
	get_tree().reload_current_scene()

func _build_picker() -> void:
	for child in picker.get_children():
		child.queue_free()

	for species in _aquarium.available_species:
		var tile := _tile(species.display_name, species.texture)
		tile.set_meta("species", species)
		tile.button_pressed = species == _aquarium.selected_species
		tile.pressed.connect(func() -> void:
			_aquarium.select_species(species)
			_refresh_hint())
		picker.add_child(tile)

	if not _aquarium.available_decor.is_empty():
		picker.add_child(_divider())
	for kind in _aquarium.available_decor:
		var tile := _tile(kind.display_name, kind.texture)
		tile.pressed.connect(func() -> void:
			_aquarium.select_decor(kind)
			_refresh_hint())
		picker.add_child(tile)

	var offered := _aquarium.placeable_factions()
	if not offered.is_empty():
		picker.add_child(_divider())
	for faction in offered:
		var tile := _tile(faction.display_name, ICON_COLONY)
		# The tile carries the faction's own colour so the strip reads as the map does:
		# picking the green one and watching green spread is the whole feedback loop.
		tile.add_theme_color_override("icon_normal_color", faction.color)
		tile.add_theme_color_override("icon_pressed_color", faction.color)
		tile.add_theme_color_override("icon_hover_color", faction.color)
		tile.pressed.connect(func() -> void:
			_aquarium.select_faction(faction)
			_refresh_hint())
		picker.add_child(tile)

	picker.add_child(_divider())
	var feed := _tile("Feed", ICON_FEED)
	feed.pressed.connect(func() -> void:
		_aquarium.set_feeding(true)
		_refresh_hint())
	picker.add_child(feed)

	var remove := _tile("Remove", ICON_REMOVE)
	remove.pressed.connect(func() -> void:
		_aquarium.set_removing(true)
		_refresh_hint())
	picker.add_child(remove)

	if not _aquarium.available_factions.is_empty():
		var strike := _tile("Strike", ICON_REMOVE)
		strike.pressed.connect(func() -> void:
			_aquarium.set_striking(true)
			_refresh_hint())
		picker.add_child(strike)

		# Separate from Strike because they are different verbs. Only Strike was on the
		# picker, so the travelling disaster the whole prototype was built and measured
		# around could not be triggered by a player at all. The bleached anemone stands
		# in for a glyph of its own until one is drawn.
		var bleach := _tile("Bleach", ICON_COLONY)
		bleach.add_theme_color_override("icon_normal_color", BLEACHED)
		bleach.add_theme_color_override("icon_pressed_color", BLEACHED)
		bleach.add_theme_color_override("icon_hover_color", BLEACHED)
		bleach.pressed.connect(func() -> void:
			_aquarium.set_bleaching(true)
			_refresh_hint())
		picker.add_child(bleach)

	_refresh_hint()

## One tile: the thing's own artwork over its name.
##
## One ButtonGroup across fish, decor and food, so arming a plant disarms the fish and a
## tap on the tank can only ever place one kind of thing.
func _tile(label: String, art: Texture2D) -> Button:
	var button := Button.new()
	button.text = label
	button.icon = art
	button.expand_icon = true
	button.vertical_icon_alignment = VERTICAL_ALIGNMENT_TOP
	button.icon_alignment = HORIZONTAL_ALIGNMENT_CENTER
	button.custom_minimum_size = Vector2(TILE_WIDTH, 0)
	# expand_icon fits the art into whatever space is left, so the height has to be
	# reserved here or a tall kelp shrinks every tile's artwork to a sliver.
	button.add_theme_constant_override("icon_max_width", TILE_ART)
	button.theme_type_variation = &"PickerTile"
	button.toggle_mode = true
	button.button_group = _group
	button.focus_mode = Control.FOCUS_NONE
	# PASS, not the Button default of STOP: a Control that stops the press keeps every
	# later event in the gesture too, so a swipe that begins on a tile — which is most
	# of the strip — never reaches the ScrollContainer and the picker cannot be
	# scrolled by the only means a phone has.
	button.mouse_filter = Control.MOUSE_FILTER_PASS
	return button

func _divider() -> VSeparator:
	var divider := VSeparator.new()
	divider.mouse_filter = Control.MOUSE_FILTER_IGNORE
	return divider

## What a tap on the water will do, in words, read back from the tank rather than
## remembered here — the picker and the tank cannot disagree about what is armed.
func _refresh_hint() -> void:
	if _aquarium.striking:
		hint.text = "Tap the reef to strike it"
	elif _aquarium.bleaching:
		hint.text = "Tap a reef to bleach it and everything it touches"
	elif _aquarium.selected_faction != null:
		var faction := _aquarium.selected_faction
		# A shoal is released into its own band of water, wherever in x the tap lands. Telling
		# the player to tap the floor for one was simply wrong.
		if faction.claim == Faction.Claim.PELAGIC:
			hint.text = "Tap the water to release a %s shoal" % faction.display_name
		else:
			hint.text = "Tap the floor to found %s" % faction.display_name
	elif _aquarium.removing:
		hint.text = "Tap a fish or plant to remove it"
	elif _aquarium.feeding:
		hint.text = "Tap the water to drop food"
	elif _aquarium.selected_decor != null:
		hint.text = "Tap the water to plant %s" % _aquarium.selected_decor.display_name
	elif _aquarium.selected_species != null:
		var name := _aquarium.selected_species.display_name
		hint.text = "Tap the water to add %s %s" % [_article(name), name]
	else:
		hint.text = "Tap the water"

## "a Anemonefish" is the sort of thing nobody notices in code and everybody notices on
## a screen. Spelling, not phonetics: no species in the roster starts with a silent h or
## a long u, and a pronunciation table for five fish would be the wrong trade.
static func _article(name: String) -> String:
	return "an" if not name.is_empty() and "aeiouAEIOU".contains(name[0]) else "a"

## Who holds how much of the sea, strongest first.
##
## Nothing on screen said who was winning. The shares were computed four times a second
## and only ever printed by the test harnesses, so a player could watch a faction lose
## half its ground and have nothing but the colour to go on. Hidden while there are no
## colonies, so a plain aquarium still looks like one.
func _on_territory_changed(_count: int) -> void:
	var territory := _aquarium.territory()
	if territory == null:
		return
	var rows: Array = []
	for faction in _aquarium.available_factions:
		var share := territory.faction_share(faction)
		if share >= MIN_STANDING:
			rows.append([faction, share])
	rows.sort_custom(func(a: Array, b: Array) -> bool: return float(a[1]) > float(b[1]))

	standings.visible = not rows.is_empty()
	# Reused rather than rebuilt: this runs four times a second.
	while standings.get_child_count() < rows.size():
		standings.add_child(_standing_label())
	for i in standings.get_child_count():
		var label := standings.get_child(i) as Label
		if i >= rows.size():
			label.visible = false
			continue
		var faction: Faction = rows[i][0]
		label.visible = true
		# One dot per trait earned, so progress along the tech tree is visible from the
		# same line that says who is winning.
		var earned := _aquarium.progress_for(faction).unlocked.size()
		label.text = "%s %d%%%s" % [faction.display_name, roundi(float(rows[i][1]) * 100.0),
			(" " + "•".repeat(earned)) if earned > 0 else ""]
		label.add_theme_color_override("font_color", faction.color.lerp(Color.WHITE, 0.2))

## One entry on the standings. Outlined, because it sits directly on the water and the
## faction colours are the same colours as the washes behind them.
func _standing_label() -> Label:
	var label := Label.new()
	label.mouse_filter = Control.MOUSE_FILTER_IGNORE
	label.add_theme_color_override("font_outline_color", Color(0.02, 0.06, 0.1, 0.9))
	label.add_theme_constant_override("outline_size", 8)
	return label

# ------------------------------------------------------------------- the feed

## One line under the standings for the things worth seeing happen: a faction evolving,
## reaching down into a basin, or dying out. Nothing said any of it before — a trait
## would change a colony's stats with no sign, and a faction could vanish unremarked.
func _build_feed() -> void:
	_feed = Label.new()
	_feed.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_feed.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	_feed.add_theme_color_override("font_outline_color", Color(0.02, 0.06, 0.1, 0.9))
	_feed.add_theme_constant_override("outline_size", 8)
	_feed.modulate.a = 0.0
	var stack := standings.get_parent()
	stack.add_child(_feed)
	stack.move_child(_feed, standings.get_index() + 1)

## Shows `text` in `tint`, then fades it. A newer event replaces an older one at once:
## a feed that queued would still be announcing a descent after the next one landed.
func announce(text: String, tint: Color) -> void:
	if _feed == null:
		return
	_feed.text = text
	_feed.add_theme_color_override("font_color", tint.lerp(Color.WHITE, 0.25))
	if _feed_tween != null:
		_feed_tween.kill()
	_feed.modulate.a = 1.0
	_feed_tween = create_tween()
	_feed_tween.tween_interval(FEED_HOLD)
	_feed_tween.tween_property(_feed, "modulate:a", 0.0, 0.8)

func feed_text() -> String:
	return _feed.text if _feed != null else ""

func _on_faction_evolved(faction: Faction, trait_: FactionTrait) -> void:
	announce("%s evolved %s: %s" % [faction.display_name, trait_.display_name,
		trait_.description], faction.color)
	if _tech_sheet != null and _tech_sheet.visible:
		_fill_tech_list()

func _on_faction_descended(from: Faction, to: Faction) -> void:
	announce("%s reached down into a basin: %s" % [from.display_name, to.display_name],
		to.color)

func _on_faction_ascended(from: Faction, to: Faction) -> void:
	announce("%s rose into open water: %s" % [from.display_name, to.display_name], to.color)

func _on_faction_extinct(faction: Faction) -> void:
	announce("%s is gone" % faction.display_name, faction.color)

# --------------------------------------------------------------- the tech sheet

## Every faction's tech tree: what it has earned, what it is working toward and how far,
## and what is still locked behind something else.
func _build_tech_sheet() -> void:
	var button := Button.new()
	button.icon = ICON_TECH
	button.tooltip_text = "Tech"
	button.custom_minimum_size = Vector2(80, 80)
	button.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	button.focus_mode = Control.FOCUS_NONE
	button.theme_type_variation = &"IconButton"
	button.name = "TechButton"
	top_bar.add_child(button)
	top_bar.move_child(button, tanks_button.get_index())
	button.pressed.connect(_toggle_tech)

	_tech_sheet = Control.new()
	_tech_sheet.name = "TechSheet"
	_tech_sheet.set_anchors_preset(Control.PRESET_FULL_RECT)
	_tech_sheet.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_tech_sheet.visible = false
	$Root.add_child(_tech_sheet)

	# Tapping outside the card closes it, as the tank switcher does.
	var scrim := ColorRect.new()
	scrim.color = Color(0.0, 0.03, 0.06, 0.55)
	scrim.set_anchors_preset(Control.PRESET_FULL_RECT)
	scrim.add_to_group("ui_blocker")
	scrim.gui_input.connect(func(event: InputEvent) -> void:
		if event is InputEventMouseButton and event.pressed:
			_toggle_tech())
	_tech_sheet.add_child(scrim)

	var margin := MarginContainer.new()
	margin.set_anchors_preset(Control.PRESET_FULL_RECT)
	margin.mouse_filter = Control.MOUSE_FILTER_IGNORE
	for side in ["left", "right", "top", "bottom"]:
		margin.add_theme_constant_override("margin_" + side, 40)
	_tech_sheet.add_child(margin)

	var card := PanelContainer.new()
	card.theme_type_variation = &"Sheet"
	card.add_to_group("ui_blocker")
	margin.add_child(card)

	var stack := VBoxContainer.new()
	stack.mouse_filter = Control.MOUSE_FILTER_IGNORE
	stack.add_theme_constant_override("separation", 14)
	card.add_child(stack)

	var header := HBoxContainer.new()
	header.mouse_filter = Control.MOUSE_FILTER_IGNORE
	stack.add_child(header)
	var title := Label.new()
	title.text = "Tech"
	title.theme_type_variation = &"Title"
	title.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	header.add_child(title)
	var close := Button.new()
	close.icon = ICON_CLOSE
	close.theme_type_variation = &"IconButton"
	close.focus_mode = Control.FOCUS_NONE
	close.custom_minimum_size = Vector2(80, 80)
	close.pressed.connect(_toggle_tech)
	header.add_child(close)

	var scroll := ScrollContainer.new()
	scroll.size_flags_vertical = Control.SIZE_EXPAND_FILL
	scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
	scroll.add_to_group("ui_blocker")
	stack.add_child(scroll)
	_tech_list = VBoxContainer.new()
	_tech_list.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_tech_list.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_tech_list.add_theme_constant_override("separation", 6)
	scroll.add_child(_tech_list)

func _toggle_tech() -> void:
	_tech_sheet.visible = not _tech_sheet.visible
	if _tech_sheet.visible:
		_fill_tech_list()

## Rebuilt on open, and whenever a trait is earned while it is open.
func _fill_tech_list() -> void:
	for child in _tech_list.get_children():
		_tech_list.remove_child(child)
		child.queue_free()
	for faction in _aquarium.available_factions:
		if faction.tech.is_empty():
			continue
		var progress := _aquarium.progress_for(faction)
		var name := _row("%s  %d of %d" % [faction.display_name, progress.unlocked.size(),
			faction.tech.size()], faction.color.lerp(Color.WHITE, 0.2))
		name.theme_type_variation = &"Title"
		_tech_list.add_child(name)
		for t in faction.tech:
			_tech_list.add_child(_row(_trait_line(progress, t), _trait_tint(progress, t)))

## What one trait says in the sheet: its name, what it does, and where it stands.
func _trait_line(progress: FactionProgress, t: FactionTrait) -> String:
	if progress.has(t):
		return "• %s: %s" % [t.display_name, t.description]
	if t.requires != null and not progress.has(t.requires):
		return "    %s: after %s" % [t.display_name, t.requires.display_name]
	var how := ""
	match t.condition:
		FactionTrait.Condition.HOLD_SHARE:
			how = "hold %d%% of the sea for %ds" % [roundi(t.threshold * 100.0), roundi(t.hold_for)]
		FactionTrait.Condition.COLONIES:
			how = "keep %d colonies for %ds" % [roundi(t.threshold), roundi(t.hold_for)]
		FactionTrait.Condition.SURVIVE_DISASTER:
			how = "live through a disaster"
		FactionTrait.Condition.HOLD_BASINS:
			how = "hold %d basin%s for %ds" % [roundi(t.threshold),
				"" if roundi(t.threshold) == 1 else "s", roundi(t.hold_for)]
	var done := progress.progress_of(t)
	var bar := (" %d%%" % roundi(done * 100.0)) if done > 0.0 else ""
	return "    %s: %s%s" % [t.display_name, how, bar]

func _trait_tint(progress: FactionProgress, t: FactionTrait) -> Color:
	if progress.has(t):
		return Color.WHITE
	if t.requires != null and not progress.has(t.requires):
		return Color(1, 1, 1, 0.38)
	return Color(1, 1, 1, 0.7)

func _row(text: String, tint: Color) -> Label:
	var label := Label.new()
	label.text = text
	label.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	label.mouse_filter = Control.MOUSE_FILTER_IGNORE
	label.add_theme_color_override("font_color", tint)
	return label

func _on_population_changed(count: int) -> void:
	population_label.text = "%d fish" % count

func _on_paused_changed(paused: bool) -> void:
	pause_button.icon = ICON_PLAY if paused else ICON_PAUSE
	pause_button.tooltip_text = "Resume" if paused else "Pause"

## Keeps the strip in step with a selection made anywhere else. Matched on the resource
## held in the tile's metadata, not on its label: two species may one day share a name,
## and a silent mismatch here shows the wrong thing armed.
func _on_species_selected(species: FishSpecies) -> void:
	for child in picker.get_children():
		var button := child as Button
		if button != null:
			button.set_pressed_no_signal(
				button.has_meta("species") and button.get_meta("species") == species)
	_refresh_hint()

## The inset on each edge (left, top, right, bottom) in screen pixels.
##
## Pure, and separated from the DisplayServer call so it can be tested: headless
## reports a degenerate safe area, so a test that drives this through the platform
## passes whatever the arithmetic does. This is where the arithmetic is checked.
##
## The rectangles are in SCREEN coordinates. Measuring the safe area against the
## WINDOW instead produced a right inset of about -970 on a windowed desktop build,
## which pushed the pause button and the whole species picker off the edges while the
## population label stayed put — it read as a layout that had never been written.
static func safe_insets(safe_area: Rect2i, screen_position: Vector2, screen_size: Vector2) -> Vector4:
	if safe_area.size.x <= 0 or safe_area.size.y <= 0 or screen_size.x <= 0.0 or screen_size.y <= 0.0:
		return Vector4.ZERO
	var wide := screen_size.x * MAX_INSET_FRACTION
	var tall := screen_size.y * MAX_INSET_FRACTION
	return Vector4(
		clampf(safe_area.position.x - screen_position.x, 0.0, wide),
		clampf(safe_area.position.y - screen_position.y, 0.0, tall),
		clampf(screen_position.x + screen_size.x - safe_area.end.x, 0.0, wide),
		clampf(screen_position.y + screen_size.y - safe_area.end.y, 0.0, tall),
	)

## Whether this platform means "the part of the screen a notch does not cover" by its
## safe area. Only the handhelds do.
##
## macOS reports the area left over after the menu bar and the Dock: 66 at the top and
## 180 at the bottom, in screen pixels, regardless of where the window is. Fed into the
## layout that is a 330px-tall control bar over a 1280px-tall tank — a fifth of the
## window is padding for a Dock that is not even behind it.
static func platform_has_cutouts() -> bool:
	return OS.get_name() in ["iOS", "Android"]

## Insets the controls past a notch or home indicator.
##
## Every margin is floored at BASE_MARGIN: a platform reporting something unexpected
## should cost a little padding, never a control the user cannot reach.
##
## The dock is inset separately from the top bar, and its panel is deliberately NOT:
## the bar itself runs to the bottom of the glass, under the home indicator, and only
## its contents step up out of the way. Insetting the panel too leaves a strip of bare
## tank below a floating bar, which reads as a layout that slipped.
func _apply_safe_area() -> void:
	var window := Vector2(DisplayServer.window_get_size())
	var view := Vector2(get_viewport().get_visible_rect().size)
	if window.x <= 0.0 or window.y <= 0.0:
		return

	var insets := Vector4.ZERO
	if platform_has_cutouts():
		var screen := DisplayServer.window_get_current_screen()
		insets = safe_insets(
			DisplayServer.get_display_safe_area(),
			Vector2(DisplayServer.screen_get_position(screen)),
			Vector2(DisplayServer.screen_get_size(screen)),
		)

	# Insets are in screen pixels; the UI is laid out in viewport units.
	var scale := view / window
	var left := BASE_MARGIN + int(insets.x * scale.x)
	var top := BASE_MARGIN + int(insets.y * scale.y)
	var right := BASE_MARGIN + int(insets.z * scale.x)
	var bottom := BASE_MARGIN + int(insets.w * scale.y)

	_set_margins(safe, left, top, right, bottom)
	_set_margins(dock_safe, left, 0, right, bottom - BASE_MARGIN)
	_set_margins(sheet_safe, left + 4, top, right + 4, bottom)

func _set_margins(node: MarginContainer, left: int, top: int, right: int, bottom: int) -> void:
	node.add_theme_constant_override("margin_left", left)
	node.add_theme_constant_override("margin_top", top)
	node.add_theme_constant_override("margin_right", right)
	node.add_theme_constant_override("margin_bottom", bottom)
